### ISSUE TITLE
MethodError: Page has no configuration data

### ISSUE THREAD

**Issue by micash545** [tombulled/python-youtube-music#24]
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.cache/pypoetry/virtualenvs/project/lib/python3.10/site-packages/ytm/apis/AbstractYouTubeMusic/AbstractYouTubeMusic.py", line 36, in __init__
    self._base    = BaseYouTubeMusic()
  File "/home/user/.cache/pypoetry/virtualenvs/project/lib/python3.10/site-packages/ytm/apis/BaseYouTubeMusic/BaseYouTubeMusic.py", line 55, in __init__
    self._update()
  File "/home/user/.cache/pypoetry/virtualenvs/project/lib/python3.10/site-packages/ytm/apis/BaseYouTubeMusic/BaseYouTubeMusic.py", line 99, in _update
    page = self.page_home()
  File "/home/user/.cache/pypoetry/virtualenvs/project/lib/python3.10/site-packages/ytm/apis/BaseYouTubeMusic/methods/page_home.py", line 30, in page_home
    return self._get_page \
  File "/home/user/.cache/pypoetry/virtualenvs/project/lib/python3.10/site-packages/ytm/apis/BaseYouTubeMusic/decorators/catch.py", line 102, in wrapper
    raise exception(exception_message)
```

**Comment by micash545** [comment]
moved to innertube
